# Core configuration
homeassistant:
  packages: !include_dir_named packages/

config:
  
http:
  server_port: 3123 #needed in my setup due to production running on default port 8123

map:
sun:
system_health:

#Uncomment to enable automations trough UI 
#automation: !include automations.yaml

#Uncomment to enable Nabu Casa
#cloud: