media_player:
  - platform: mopidy
    name: MPD Balcony
    host: 192.168.0.30
    port: 6684

# Light switch template to transform switch. into light. entity
light:
  - platform: switch
    name: balcony_ceiling
    entity_id: switch.light_balcony

input_boolean:
  # Do not Disturb Boolean
  dnd_balcony:
    name: DnD Balkon
    icon: mdi:cancel
  
# Entity Customization
homeassistant:
  customize:
    # Lights
    light.balcony_ceiling:
      friendly_name: Lichterkette
      icon: mdi:string-lights
    # Media Players
    media_player.mpd_balcony:
      friendly_name: MPD Balkon
    media_player.snapclient_balcony:
      friendly_name: Snapclient Balkon
    media_player.music_balcony:
      friendly_name: Musik Balkon
    # Environment Sensors
    sensor.lux_outside:
      friendly_name: Aussen
      icon: mdi:weather-sunny
      device_class: illuminance
      unit_of_measurement: "lx"
    # Battery Sensors
    sensor.battery_level_lux_outside:
      friendly_name: Lux Sensor Aussen
