# Light switch template to transform switch. into light. entity
light:
  - platform: switch
    name: Lichterkette Balkon
    entity_id: switch.plug_balkon

# Entity Customization
homeassistant:
  customize:
    # Lights
    light.lichterkette_balkon:
      friendly_name: Lichterkette
      icon: mdi:string-lights
