# Light switch template to transform switch. into light. entity
light:
  - platform: switch
    name: balcony_ceiling
    entity_id: switch.plug_balkon

# Entity Customization
homeassistant:
  customize:
    # Lights
    light.balcony_ceiling:
      friendly_name: Lichterkette
      icon: mdi:string-lights
