input_boolean:
  # Do not Disturb Boolean
  dnd_bedroom:
    name: DnD Schlafzimmer
    icon: mdi:cancel

binary_sensor:
  - platform: template
    sensors:
      # Room Occupancy
      occupancy_bedroom:
        friendly_name: Schlafzimmer besetzt
        device_class: occupancy
        value_template: >-
          {% set motion = is_state('binary_sensor.motion_bedroom', 'on') %}
          {% set sleep = is_state('input_boolean.sleep_mode', 'on') %}
          {{ motion or sleep }}
        delay_off:
          minutes: 10

sensor:
  # Custom Integration Powercalc
  ## Power consumption lights
  - platform: powercalc
    name: power_light_bedroom_ceiling
    entity_id: light.bedroom_ceiling
    manufacturer: signify
    model: LCT010
    multiply_factor: 3
  - platform: powercalc
    name: power_light_bedroom_bed
    entity_id: light.bedroom_bed
    linear:
      min_power: 0.5
      max_power: 20
    standby_usage: 0.4

automation:
  # Turn lights on (if not already on) when motion is detected
  # Sleep Mode Enabled -> Turn on light strip under the bed
  # Sleep Mode Disabled -> Turn on ceiling light
  - id: motion_light_on_bedroom
    alias: "Licht an bei Bewegung - Schlafzimmer"
    mode: single
    trigger:
      platform: state
      entity_id: binary_sensor.motion_bedroom
      to: "on"
    condition: "{{ is_state('light.bedroom', 'off') }}"
    action:
      - choose:
          # IF sleep mode-> turn on underbed light
          - conditions:
              - "{{ is_state('input_boolean.sleep_mode', 'on') }}"
            sequence:
              - service: light.turn_on
                entity_id: light.bedroom_bed
        # ELSE turn on ceiling light
        default:
          - service: light.turn_on
            entity_id: light.bedroom_ceiling

  # Turn lights off when room is not occupied anymore
  - id: no_occupancy_light_off_bedroom
    alias: "Licht aus Schlafzimmer nicht besetzt"
    mode: single
    trigger:
      platform: state
      entity_id: binary_sensor.occupancy_bedroom
      to: "off"
    condition: "{{ is_state('light.bedroom', 'off') }}"
    action:
      service: light.turn_off
      entity_id: light.bedroom

  # Turn adaptive sleep lighting on/off when sleep mode is enabled/disabled
  - id: sleep_mode_turn_on_adaptive_sleep_bedroom
    alias: "Schlafmodus f체r adaptive Beleuchtung Schlafzimmer"
    mode: single
    trigger:
      platform: state
      entity_id: input_boolean.sleep_mode
    action:
      service: "switch.turn_{{ trigger.to_state.state }}"
      entity_id: switch.adaptive_lighting_sleep_mode_bedroom_bed

  # Light Remote Bedroom
  - id: 'remote_light_bedroom'
    alias: "Licht Schalter Schlafzimmer"
    use_blueprint:
      path: custom/hue_dimmer_light.yaml
      input:
        transition_time_dim: '5'
        remote: remote_light_bedroom
        light: light.bedroom

  # Remote Sabrina
  - id: 'remote_sabrina'
    alias: "Fernbedienung Sabrina"
    use_blueprint:
      path: custom/hue_dimmer_general.yaml
      input:
        remote: remote_sabrina
        short_press_turn_on:
          - service: light.turn_on
            entity_id: light.bedroom_bed
        long_press_turn_on:
          - service: light.turn_on
            entity_id: light.bedroom_ceiling
        short_press_turn_off:
          - service: script.turn_on
            entity_id: script.turn_all_off

  # Remote Dimitri
  - id: 'remote_dimitri'
    alias: "Fernbedienung Dimitri"
    use_blueprint:
      path: custom/hue_dimmer_general.yaml
      input:
        remote: remote_dimitri
        short_press_turn_on:
          - service: light.turn_on
            entity_id: light.bedroom_bed
        long_press_turn_on:
          - service: light.turn_on
            entity_id: light.bedroom_ceiling
        short_press_turn_off:
          - service: script.turn_on
            entity_id: script.turn_all_off

# Entity Customization
homeassistant:
  customize:
    # Lights
    light.bedroom:
      friendly_name: Schlafzimmer
      icon: mdi:lightbulb
    light.bedroom_ceiling:
      friendly_name: Deckenlampe
      icon: mdi:ceiling-light
    light.bedroom_bed:
      friendly_name: LED Bett
      icon: mdi:led-strip-variant
    # Media Players
    media_player.mpd_bedroom:
      friendly_name: MPD Schlafzimmer
    media_player.snapclient_bedroom:
      friendly_name: Snapclient Schlafzimmer
    media_player.music_bedroom:
      friendly_name: Musik Schlafzimmer
    # Door/Window Sensor
    binary_sensor.window_bedroom:
      friendly_name: Fenster Schlafzimmer
      device_class: window
    binary_sensor.door_bedroom:
      friendly_name: T체r Schlafzimmer
      device_class: door
    # Motion/Tamper Sensors
    binary_sensor.motion_bedroom:
      friendly_name: Schlafzimmer
      device_class: motion
    binary_sensor.tamper_bedroom:
      friendly_name: Manipulation Schlafzimmer
      device_class: safety
    # Environment Sensors
    sensor.temperature_bedroom:
      friendly_name: Schlafzimmer
      device_class: temperature
      unit_of_measurement: "째C"
    sensor.humidity_bedroom:
      friendly_name: Schlafzimmer
      device_class: humidity
      unit_of_measurement: "%"
    # Battery Sensors
    sensor.battery_level_door_bedroom:
      friendly_name: T체r Sensor Schlafzimmer
    sensor.battery_level_window_bedroom:
      friendly_name: Fenster Sensor Schlafzimmer
    sensor.battery_level_multisensor_bedroom:
      friendly_name: Multisensor Schlafzimmer
    sensor.battery_level_remote_light_bedroom:
      friendly_name: Remote Licht Schlafzimmer
    sensor.battery_level_remote_sabrina:
      friendly_name: Remote Sabrina
    sensor.battery_level_remote_dimitri:
      friendly_name: Remote Dimitri
    # Applicances
    switch.dehumidifier_bedroom:
      friendly_name: Entfeuchter
      icon: mdi:power-plug

