# Entity Customization
homeassistant:
  customize:
    # Lights
    light.bedroom_ceiling:
      friendly_name: Deckenlampe
      icon: mdi:ceiling-light
    light.bedroom_bed:
      friendly_name: Bett
      icon: mdi:led-strip-variant
