# Internal and External URL configuration
homeassistant:
  internal_url: http://192.168.0.30:3123
  external_url: !secret external_HA_URL
  
http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - 172.19.0.7
  ip_ban_enabled: true
  login_attempts_threshold: 5

tts:
  - platform: google_translate
    language: 'de'
    base_url: !secret external_HA_URL