energy:

input_number:
  # Electricity peak price
  electricity_price_peak:
    name: Strompreis HT kWh
    min: 0
    max: 2
    step: 0.01
  # Electricity off-peak price
  electricity_price_off_peak:
    name: Strompreis NT kWh
    min: 0
    max: 2
    step: 0.01

sensor:
  # Custom Integration Powercalc
  ## Power consumption bedroom lights
  - platform: powercalc
    name: power_light_bedroom_ceiling_1
    entity_id: light.bedroom_ceiling_1
    manufacturer: signify
    model: LCT010
  - platform: powercalc
    name: power_light_bedroom_ceiling_2
    entity_id: light.bedroom_ceiling_2
    manufacturer: signify
    model: LCT010
  - platform: powercalc
    name: power_light_bedroom_ceiling_3
    entity_id: light.bedroom_ceiling_3
    manufacturer: signify
    model: LCT010
  - platform: powercalc
    name: power_light_bedroom_bed
    entity_id: light.bedroom_bed
    linear:
      min_power: 0.5
      max_power: 20
    standby_usage: 0.4
  ## Power consumption dressroom lights
  - platform: powercalc
    name: power_light_dressroom_ceiling_1
    entity_id: light.dressroom_ceiling_1
    manufacturer: signify
    model: LCT010
  - platform: powercalc
    name: power_light_dressroom_ceiling_2
    entity_id: light.dressroom_ceiling_2
    manufacturer: signify
    model: LCT010
  - platform: powercalc
    name: power_light_dressroom_ceiling_3
    entity_id: light.dressroom_ceiling_3
    manufacturer: signify
    model: LCT010
  ## Power consumption livingroom lights
  - platform: powercalc
    name: power_light_livingroom_floor_front
    entity_id: light.livingroom_floor_front
    manufacturer: signify
    model: LCT010
  - platform: powercalc
    name: power_light_livingroom_floor_back
    entity_id: light.livingroom_floor_back
    manufacturer: signify
    model: LCT010
  ## Power consumption office lights
  - platform: powercalc
    name: power_light_office_ceiling_1
    entity_id: light.office_ceiling_1
    linear:
      min_power: 0.5
      max_power: 5
    standby_usage: 0.2
  - platform: powercalc
    name: power_light_office_ceiling_2
    entity_id: light.office_ceiling_2
    linear:
      min_power: 0.5
      max_power: 5
    standby_usage: 0.2
  - platform: powercalc
    name: power_light_office_ceiling_3
    entity_id: light.office_ceiling_3
    linear:
      min_power: 0.5
      max_power: 5
    standby_usage: 0.2

  # Convert power (W) to energy (kWh) 
  - platform: integration
    source: sensor.power_lights
    name: energy_lights
    unit_prefix: k
    round: 2

template:
  - sensor:
      # Power consumption of all lights
      - name: power lights
        device_class: power
        unit_of_measurement: W
        state: >
          {% set office = states('sensor.power_light_office_ceiling_1')|float + states('sensor.power_light_office_ceiling_2')|float + states('sensor.power_light_office_ceiling_3')|float %}
          {% set bedroom_ceiling = states('sensor.power_light_bedroom_ceiling_1')|float + states('sensor.power_light_bedroom_ceiling_2')|float + states('sensor.power_light_bedroom_ceiling_3')|float  %}
          {% set bedroom_bed = states('sensor.power_light_bedroom_bed')|float %}
          {% set dressroom = states('sensor.power_light_dressroom_ceiling_1')|float + states('sensor.power_light_dressroom_ceiling_2')|float + states('sensor.power_light_dressroom_ceiling_3')|float %}
          {% set livingroom = states('sensor.power_light_livingroom_floor_front')|float + states('sensor.power_light_livingroom_back')|float %}
          {{ office + bedroom_ceiling + bedroom_bed + dressroom + livingroom }}
      # Current Electricity Tariff
      - name: electricity tariff
        device_class: monetary
        unit_of_measurement: CHF
        state: >
          {% set day = now().weekday() %}
          {% set hour = now().hour %}
          {% if (day == 5 and 7 <= hour < 13) or (day < 5 and 7 <= hour < 20) %}
            Hochtarif
          {% else %}
            Niedertarif
          {% endif %}
      # Current Electricity Price
      - name: electricity price
        device_class: monetary
        unit_of_measurement: CHF
        state: >
          {% set peak_price = states('input_number.electricity_price_peak') %}
          {% set off_peak_price = states('input_number.electricity_price_off_peak') %}
          {% set tariff = states('sensor.electricity_tariff') %}
          {% if tariff == "Hochtarif" %}
            {{ peak_price }}
          {% else %}
            {{ off_peak_price }}
          {% endif %}

# Utility Meter Lights
utility_meter:
  energy_quarterly_lights:
    source: sensor.energy_quarterly_lights
    cycle: quarterly
    tariffs:
      - Hochtarif
      - Niedertarif

automation:
  # Set Electricity Tariff
  - id: set_tariffs
    alias: Stromtarif Update
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.electricity_tariff
    action:
      - service: utility_meter.select_tariff
        target:
          entity_id: 
            - utility_meter.energy_quarterly_dishwasher
            - utility_meter.energy_quarterly_lights
        data:
          tariff: "{{ trigger.to_state.state }}"

# Entity Customization
homeassistant:
  customize:
    # Tariff
    sensor.electricity_tariff:
      friendly_name: Stromtarif
    # Electricity Price
    sensor.electricity_price:
      friendly_name: Strompreis
    # Energy Lights
    sensor.energy_lights:
      friendly_name: Konsum Licht