# Entity Customization
homeassistant:
  customize:
    # Lights
    light.livingroom_floor_front:
      friendly_name: Vorne
      icon: mdi:floor-lamp
    light.livingroom_floor_back:
      friendly_name: Hinten
      icon: mdi:floor-lamp