emulated_roku:
  servers:
    - name: Roku
      listen_port: 8060
      host_ip: 10.10.40.6

input_boolean:
  # Do not Disturb Boolean
  dnd_livingroom:
    name: DnD Wohnzimmer
    icon: mdi:cancel

binary_sensor:
  - platform: template
    sensors:
      # Room Occupancy
      occupancy_livingroom:
        friendly_name: Wohnzimmer besetzt
        device_class: occupancy
        value_template: >-
          {% set motion = is_state('binary_sensor.motion_livingroom', 'on') %}
          {% set tv = is_state('remote.wohnzimmer', 'on') %}
          {{ motion or tv }}
        delay_off:
          minutes: 10

sensor:
  # Custom Integration Powercalc
  ## Power consumption lights
  - platform: powercalc
    name: power_light_livingroom_floor_front
    entity_id: light.livingroom_floor_front
    manufacturer: signify
    model: LCT010
  - platform: powercalc
    name: power_light_livingroom_floor_back
    entity_id: light.livingroom_floor_back
    manufacturer: signify
    model: LCT010
  ## Power consumption beamer
  - platform: powercalc
    name: power_beamer
    entity_id: sensor.current_activity_livingroom
    fixed:
      states_power:
        Fernsehen: 364
        Nintendo Switch: 364
        Musik: 0.4
        Filme/Serien: 364
        PowerOff: 0.4
  ## Power consumption AV Receiver
  - platform: powercalc
    name: power_receiver_livingroom
    entity_id: media_player.receiver_livingroom
    standby_usage: 2.7
    fixed:
      power: 500
  # Convert power (W) to energy (kWh) for beamer
  - platform: integration
    source: sensor.power_beamer
    name: energy_beamer
    unit_prefix: k
    round: 2
  # Convert power (W) to energy (kWh) for AV Receiver
  - platform: integration
    source: sensor.power_receiver_livingroom
    name: energy_receiver_livingroom
    unit_prefix: k
    round: 2

template:
  - sensor:
      # Current activity of harmony remote
      - name: current activity livingroom
        state: "{{ state_attr('remote.wohnzimmer', 'current_activity') }}"

automation:
  # Turn lights on (if not already on) when motion is detected
  - id: motion_light_on_livingroom
    alias: "Licht an bei Bewegung - Wohnzimmer"
    mode: single
    trigger:
      platform: state
      entity_id: binary_sensor.motion_livingroom
      to: "on"
    condition: "{{ is_state('light.livingroom', 'off') }}"
    action:
      service: light.turn_on
      entity_id: light.livingroom
      
  # Turn lights off when room is not occupied anymore
  - id: no_occupancy_light_off_livingroom
    alias: "Licht aus Wohnzimmer nicht besetzt"
    mode: single
    trigger:
      platform: state
      entity_id: binary_sensor.occupancy_livingroom
      to: "off"
    condition: "{{ is_state('light.livingroom', 'on') }}"
    action:
      service: light.turn_off
      entity_id: light.livingroom

  # Light Remote Livingroom
  - id: 'remote_light_livingroom'
    alias: "Licht Schalter Wohnzimmer"
    use_blueprint:
      path: custom/hue_dimmer_light.yaml
      input:
        transition_time_dim: '5'
        remote: remote_light_livingroom
        light: light.livingroom

# Entity Customization
homeassistant:
  customize:
    # Lights
    light.livingroom:
      friendly_name: Wohnzimmer
      icon: mdi:lightbulb
    light.livingroom_floor_front:
      friendly_name: Vorne
      icon: mdi:floor-lamp
    light.livingroom_floor_back:
      friendly_name: Hinten
      icon: mdi:floor-lamp
    # Media Players
    media_player.mpd_livingroom:
      friendly_name: MPD Wohnzimmer
    media_player.snapclient_livingroom:
      friendly_name: Snapclient Wohnzimmer
    media_player.kodi_livingroom:
      friendly_name: Medien Wohnzimmer
    media_player.receiver_livingroom:
      friendly_name: Verstärker Wohnzimmer
    # Remotes
    remote.wohnzimmer:
      friendly_name: Fernbedienung Wohnzimmer
    # Door/Window Sensor
    binary_sensor.window_livingroom:
      friendly_name: Fenster Wohnzimmer
      device_class: window
    binary_sensor.door_livingroom:
      friendly_name: Tür Wohnzimmer
      device_class: door
    # Motion/Tamper Sensors
    binary_sensor.motion_livingroom:
      friendly_name: Wohnzimmer
      device_class: motion
    # Environment Sensors
    sensor.temperature_livingroom:
      friendly_name: Wohnzimmer
      device_class: temperature
      unit_of_measurement: "°C"
    sensor.humidity_livingroom:
      friendly_name: Wohnzimmer
      device_class: humidity
      unit_of_measurement: "%"
    # Battery Sensors
    sensor.battery_level_door_livingroom:
      friendly_name: Tür Sensor Wohnzimmer
    sensor.battery_level_window_livingroom:
      friendly_name: Fenster Sensor Wohnzimmer
    sensor.battery_level_motion_livingroom:
      friendly_name: Bewegung Sensor Wohnzimmer
    sensor.battery_level_temperature_livingroom:
      friendly_name: Temperatur Sensor Wohnzimmer
    sensor.battery_level_remote_light_livingroom:
      friendly_name: Remote Licht Wohnzimmer
    # Energy Sensors
    sensor.energy_beamer:
      friendly_name: Konsum Beamer
    sensor.energy_receiver_livingroom:
      friendly_name: Konsum Verstärker Wohnzimmer
