# # Yamaha MusicCast Receiver
# media_player:
#   platform: yamaha_musiccast
#   host: 10.10.80.7
# media_player:
#   - platform: mpd
#     name: MPD Office
#     host: 192.168.0.30
#     port: 6603

media_player:
  - platform: mopidy
    name: MPD Office
    host: 192.168.0.30
    port: 6683

binary_sensor:
  - platform: template
    sensors:
      # Room Occupancy
      # add persons once Fitbits are integrated by adding the following line:
      # {% set persons = expand('group.room_presence_sensors') | selectattr('state', 'eq', 'office') | list | length > 0 %}
      # and adding "or persons" to the last line of the template
      occupancy_office:
        friendly_name: Büro besetzt
        device_class: occupancy
        value_template: >-
          {% set motion = is_state('binary_sensor.motion_office', 'on') %}
          {% set deskhim = is_state('device_tracker.desktop_dimitri', 'home') %}
          {% set deskher = is_state('device_tracker.desktop_sabrina', 'home') %}
          {% set laptopwork = is_state('device_tracker.laptop_work', 'home') %}
          {{ motion or deskhim or deskher or laptopwork }}
        delay_off:
          minutes: 15

automation:
  # Turn lights on (if not already on) when motion is detected and lux below threshold
  - id: motion_light_on_office
    alias: "Licht an bei Bewegung - Büro"
    mode: single
    trigger:
      platform: state
      entity_id: binary_sensor.motion_office
      to: "on"
    condition:
      - "{{ is_state('light.office', 'off') }}"
      - condition: numeric_state
        entity_id: sensor.lux_office
        below: 200
    action:
      service: light.turn_on
      entity_id: light.office

  # Turn lights off when room is not occupied anymore
  - id: no_occupancy_light_off_office
    alias: "Licht aus Büro nicht besetzt"
    mode: single
    trigger:
      platform: state
      entity_id: binary_sensor.occupancy_office
      to: "off"
    condition: "{{ is_state('light.office', 'on') }}"
    action:
      service: light.turn_off
      entity_id: light.office

  # Light Remote Office
  - id: 'remote_light_office'
    alias: "Licht Schalter Büro"
    use_blueprint:
      path: custom/hue_dimmer_light.yaml
      input:
        transition_time_dim: '5'
        remote: remote_light_office
        light: light.office

# Entity Customization
homeassistant:
  customize:
    # Lights
    light.office:
      friendly_name: Deckenlampe
      icon: mdi:ceiling-light
    # Media Players
    media_player.mpd_office:
      friendly_name: MPD Büro
    media_player.snapclient_office:
      friendly_name: Snapclient Büro
    media_player.music_office:
      friendly_name: Musik Büro
    # Door/Window Sensor
    binary_sensor.window_office:
      friendly_name: Fenster Büro
      device_class: window
    binary_sensor.door_office:
      friendly_name: Tür Büro
      device_class: door
    # Motion/Tamper Sensors
    binary_sensor.motion_office:
      friendly_name: Büro
      device_class: motion
    binary_sensor.tamper_office:
      friendly_name: Manipulation Büro
      device_class: safety
    # Environment Sensors
    sensor.lux_office:
      friendly_name: Büro
      icon: mdi:weather-sunny
      device_class: illuminance
      unit_of_measurement: "lx"
    sensor.temperature_office:
      friendly_name: Büro
      device_class: temperature
      unit_of_measurement: "°C"
    sensor.humidity_office:
      friendly_name: Büro
      device_class: humidity
      unit_of_measurement: "%"
    # Battery Sensors
    sensor.battery_level_lux_office:
      friendly_name: Lux Sensor Büro
    sensor.battery_level_door_office:
      friendly_name: Tür Sensor Büro
    sensor.battery_level_window_office:
      friendly_name: Fenster Sensor Büro
    sensor.battery_level_remote_light_office:
      friendly_name: Remote Licht Büro

