# Entity Customization
homeassistant:
  customize:
    # Lights
    light.office:
      friendly_name: Deckenlampe
      icon: mdi:ceiling-light
    # Door/Window Sensor
    binary_sensor.window_office:
      friendly_name: Fenster Büro
      device_class: window
    binary_sensor.door_office:
      friendly_name: Tür Büro
      device_class: door
    # Motion/Tamper Sensors
    binary_sensor.motion_office:
      friendly_name: Büro
      device_class: motion
    binary_sensor.tamper_office:
      friendly_name: Manipulation Büro
      device_class: safety
    # Environment Sensors
    sensor.lux_office:
      friendly_name: Büro
      icon: mdi:weather-sunny
      device_class: illuminance
      unit_of_measurement: "lx"
    sensor.temperature_office:
      friendly_name: Büro
      device_class: temperature
      unit_of_measurement: "°C"
    sensor.humidity_office:
      friendly_name: Büro
      device_class: humidity
      unit_of_measurement: "%"
    # Battery Sensors
    sensor.battery_level_lux_office:
      friendly_name: Lux Sensor Büro
    sensor.battery_level_door_office:
      friendly_name: Tür Sensor Büro
    sensor.battery_level_window_office:
      friendly_name: Fenster Sensor Büro
    sensor.battery_level_remote_light_office:
      friendly_name: Remote Lichtr Büro
