# Person Integration
person:

# Bluetooth Room Presence Tracker
device_tracker:
  platform: mqtt
  devices:
    room_presence_dimitri: 'location/dimitri_room_presence'
    room_presence_sabrina: 'location/sabrina_room_presence'
  source_type: bluetooth_le

# GPS Presence Tracker (Phone App)
mobile_app:

# Entity Customization
homeassistant:
  customize:
    zone.home:
      friendly_name: Zu Hause
      icon: mdi:home
    # Dimitri
    person.dimitri:
      friendly_name: Dimitri
      entity_picture: /local/person_pictures/dimitri_home.jpg
      icon: mdi:account
    ## Phone
    sensor.battery_level_phone_dimitri:
      friendly_name: Handy Dimitri
    sensor.charging_phone_dimitri:
      friendly_name: Ladestatus Handy Dimitri
      icon: mdi:cellphone-charging
    sensor.next_alarm_phone_dimitri:
      friendly_name: Nächster Wecker Dimitri
      icon: mdi:alarm
    sensor.call_state_phone_dimitri:
      friendly_name: Anruf Dimitri
      icon: mdi:phone
    sensor.wifi_connection_phone_dimitri:
      friendly_name: WiFi Handy Dimitri
    ## Presence
    device_tracker.gps_presence_dimitri:
      friendly_name: Standort Dimitri
      icon: mdi:map-marker
    device_tracker.room_presence_dimitri:
      friendly_name: Schlüssel Dimitri
      icon: mdi:key
    zone.work_dimitri:
      friendly_name: Arbeit
      icon: mdi:office-building
    # Sabrina
    person.sabrina:
      friendly_name: Sabrina
      entity_picture: /local/person_pictures/sabrina_home.jpg
      icon: mdi:account
    device_tracker.room_presence_sabrina:
      friendly_name: Schlüssel Sabrina
      icon: mdi:key