alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    delay_time: 0
    trigger_time: 100
    disarmed:
      trigger_time: 0
    armed_home:
      delay_time: 0
    disarm_after_trigger: false